server:
  #微服务端口
  port: 7006
spring:
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1

  application:
    name: sqa-cloud-access-handler

jwt:
  config:
    key: saas-ihrm
    ttl: 3600000
tepm:
  version: v0.0.1-SNAPSHOT
  remarks: 这是v0.0.1-SNAPSHOT版本
